# Generated by Django 3.0.5 on 2021-04-22 11:22

import board.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tags', djongo.models.fields.EmbeddedField(model_container=board.models.Tag)),
                ('comments', djongo.models.fields.EmbeddedField(model_container=board.models.Comment)),
            ],
        ),
    ]
